spring.application.name=auth-service

spring.datasource.url=jdbc:mysql://localhost:3307/auth_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

#Production mode
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
# never

server.port=8081

spring.profiles.active=local

spring.security.user.name=diana
spring.security.user.password=password

jwt.secret=${JWT_SECRET}
jwt.access-expiry-minutes=1

auth.refresh-expiry-days=7
auth.internal-key=${AUTH_INTERNAL_KEY}

spring.jackson.default-property-inclusion=non_null

